services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: transcendence
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s

  django:
    build: ./backend/backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/transcendence
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - mynetwork
    depends_on:
      - django

  redis:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge
